coffer.cabal, lib/Backend.hs, lib/Backend/Vault/Kv.hs, lib/CLI/Parser.hs, lib/CLI/Types.hs, lib/Coffer/Path.hs, lib/Entry.hs, lib/Entry/Json.hs, package.yaml
This PR implements the parsers needed for the CLI and adds a couple of newtypes for type-safety (`PathSegment`, `Path`, `EntryPath`, `FieldVisibility`).
=> [#29] Add CLI parser

app/Main.hs, lib/Backend/Commands.hs, lib/CLI/Types.hs, lib/Coffer/Path.hs, tests/golden/create-command/create-command.bats
Problem: we can create entries and directories with the same names.
Solution: added subfunction `checkForEntriesInEntryPath` which tries to find an existing entry subpath in given path. Then checked if the given entry path is an existing directory or contains existing entries in subpaths.
[//]: # (For GitHub/GitLab issues it is better to use just hash symbol or exclamation mark as it is more …
=> [#9] Directory check in `create` command

lib/CLI/Parser.hs, tests/golden/view-command/view-command.bats
Problem: `view` will be the command users use the most. It would be better to make it the default command.
Solution: made `view` command by default.
[//]: # (See …
=> [#3] Supported `view` command by default

tests/golden/copy-command/config.toml, tests/golden/create-command/config.toml, tests/golden/delete-command/config.toml, tests/golden/delete-field-command/config.toml, tests/golden/find-command/config.toml, tests/golden/helpers.bash, tests/golden/set-field-command/config.toml, tests/golden/tag-command/config.toml, tests/golden/view-command/config.toml
Problem: `bats` tests are failing because there is no `config.toml` file.
Solution: added `config.toml` config in each directory.
[//]: # (See …
=> [#40] Added `config.toml` configs in `bats` tests directories

app/Main.hs, lib/Backend/Commands.hs, tests/golden/rename-command/rename-command.bats
Problem: `rename` command is not implemented.
Solution: implemented `rename` command via `copy` and `delete` commands.
Fixes: #12
=> [#12] Rename command implemented

app/Main.hs, lib/Backend/Commands.hs, lib/CLI/Types.hs, tests/golden/copy-command/copy-command.bats, tests/golden/create-command/create-command.bats, tests/golden/rename-command/config.toml, tests/golden/rename-command/rename-command.bats
Problem: there were no checks for entries in destination subpaths in `copy` command.
Solution: created subfunction `checkForEntriesInPath`, which validates that there are no entries in subpaths of a given path.
Fixes #11
=> [#11] Checking for entries in destination subpaths in `copy` command

app/Main.hs, lib/CLI/Parser.hs, lib/CLI/Types.hs
Problem: you cannot use multiple configs for `coffer`.
Solution: added optional argument `[-c|--config]` to specify your config path.
Fixed: #19
=> [#19] Config path specifying supported

app/Main.hs, tests/golden/find-command/find-command.bats, tests/golden/set-field-command/set-field-command.bats, tests/golden/view-command/view-command.bats
=> [#38] Displaying fix in `set-field` command

coffer.cabal, lib/Backend/Commands.hs, lib/Backend/Vault/Kv.hs, lib/CLI/Parser.hs, lib/CLI/PrettyPrint.hs, lib/CLI/Types.hs, lib/Entry.hs, lib/Entry/Json.hs, package.yaml, tests/golden/find-command/find-command.bats, tests/golden/helpers.bash, tests/golden/set-field-command/set-field-command.bats, tests/golden/view-command/view-command.bats
=> [#48] Appending reset ANSI control sequences char after printing field value

scripts/run-bats-tests.sh, tests/golden/default-config.toml
=> [#61] Fixed bug with second `vault` instance in `run-bats-tests.sh`

lib/CLI/Parser.hs, tests/golden/common/common.bats, tests/golden/create-command/create-command.bats
=> [#49] Escaping characters in parse errors

app/Main.hs, lib/Backend/Commands.hs, lib/CLI/Types.hs, lib/Coffer/Path.hs, tests/golden/copy-command/copy-command.bats, tests/golden/delete-command/delete-command.bats, tests/golden/rename-command/rename-command.bats, tests/golden/set-field-command/set-field-command.bats
=> [#52] Show qualified paths in `coffer` messages

app/Main.hs, lib/Backend/Commands.hs, lib/Backend/Vault/Kv.hs, lib/Error.hs
=> [#24] Better error handling

.buildkite/pipeline.yml
Problem: The `validate cabal files` build step hasn't been working ever
since we added it. We can see this message in the logs:
```
./scripts/validate-cabal-files.sh: line 39: diff: command not found
```
The reason why the build step did not actually ever fail (thus, it was a false
negative) is because we temporarily use `set +e` to mask all non-zero
exit codes.
Solution: add the missing `diffTools` to the nix shell.
Fixed part of #26 
- Tests
- Haddock
=> [#26] Fix `validate cabal files` CI step

lib/Backend/Commands.hs
At this moment `rename` command reuses `delete` command,
so we do some unnecessary actions like `getEntryOrDirThrow`.
Replaced `deleteCmd` call with `deleteSecret`.
- Fixes #66
Fixed #
- Tests
- Haddock
=> [#66] Rename command optimization

lib/Backend/Commands.hs, lib/Backend/Vault/Kv.hs, lib/CLI/Parser.hs, lib/Entry.hs, lib/Error.hs
There are 2 problems here:
- In the `Backend.Vault.Kv` module, we're constructing `OtherError` with user-facing error messages as strings.
- `CofferError` is meant to be backend-agnostic, but it assumes that all backends will (possibly) throw a `ServantError`. However, the `pass` backend, for example, does not use servant.
1. Used ADTs + Buildable to model errors.
2. Made `CofferError` backend-agnostic.
3. Created backend-specific error type class.
- Fixes #72.
Fixed #
- Tests
- Haddock
=> [#72] Backend-agnostic `CofferError` GADT

app/Main.hs, lib/Backend/Commands.hs, lib/CLI/Types.hs, lib/Coffer/Path.hs, tests/golden/copy-command/copy-command.bats, tests/golden/rename-command/rename-command.bats
Currently copying entry / directory to itself is allowed in force mode.
This copying is very unnecessary, we can't see such behavior in
standard Unix `cp` command. The same applies to renaming
entries to it's current name.
Check qualified paths for equality before copying.
Fixed #22 
- Tests
- Haddock
=> [#22] Copy with equal paths behavior fix

nix/sources.json
Problem: For some reason, when I added `sources.json` to the project, I
used the sha256 of an older version of xrefcheck.
Solution: Use the correct hash for the version of xrefcheck we're using
None
- Tests
- Haddock
=> [Chore] Fix xrefcheck's hash in sources.json

lib/Backend/Commands.hs, lib/CLI/Parser.hs, lib/CLI/Types.hs, tests/golden/common/common.bats, tests/golden/find-command/find-command.bats
@Heimdell in #44 suggested to merge --filter and --filter-field options into a single --filter option.
e.g.:
```
--filter name~vault               <- filter entries by entry name
--filter url:value~google.com     <- filter entries by field value
```
Modified `parseFilter :: MParser Filter` supplementing it with `parseFilterByField`'s functionality.
Changed related datatypes so there is no separation between `filter` and `filter-field`.
- Fixed part of #44:
- Tests
- Haddock
=> [#44] Merge `--filter` and `--filter-field` options

lib/CLI/Parser.hs, tests/golden/find-command/find-command.bats
Problem : Parse error messages in `find --sort` and `find --find` had different styles
Solution : rewrote `sort` parsing to Megaparsec instead of `splitOn(":")`
Fixed #98 
- Tests
- Haddock
=> [#98] One style errors

lib/Backend.hs, lib/Backend/Commands.hs, lib/Backend/Vault/Kv.hs, lib/Coffer/Path.hs, lib/Error.hs
At this moment the `listDirectoryContents` function returns `[Text]`
and in `getEntryOrDir` we rely on the fact that `vault` adds a '/'
to the directory. But other backends might not behave like this.
Created new data `DirectoryContents` which stores 2 lists:
1. list with directories
2. list with entries
and changed return type from `Maybe [Text]` to `Maybe DirectoryContents`
in `listDirectoryContents` function.
- Fixes #106 
Fixed #
- Tests
- Haddock
=> [#106] Backend-agnostic `listDirectoryContents`

coffer.cabal, lib/BackendName.hs, lib/CLI/Types.hs, lib/Coffer/Directory.hs, lib/Coffer/Path.hs, lib/Entry.hs, package.yaml, tests/server-integration/Integration.hs, tests/server-integration/Utils.hs
At this moment `ToJSON` instances leak a lot of internal info.
Some of them look very ugly (e.g. `EntryPath`).
Used `deriveToJSON (aesonPrefix camelCase)` to derive some instances.
`QualifiedPath` `ToJSON` instance is handcrafted. Also removed unnecessary
`FromJSON` instances.
- Fixes #82 
Fixed #
- Tests
- Haddock
=> [#82] Pretty `ToJSON` instances

coffer.cabal, lib/Backend/Commands.hs, lib/CLI/Types.hs, lib/Coffer/PrettyPrint.hs, lib/Web/API.hs, lib/Web/Server.hs, package.yaml, tests/server-integration/Integration.hs
At this moment in Web API in all endpoints (except for `find`)
we return the corresponding result from `CLI.Types`.
But it seems not correct, because these results contain
both success and errors. And API should return only success results
(error results return in corresponding handlers).
Changed endpoints results to `Entry | Directory`. Some changes
demanded changes in `CLI.Types` (e.g. returning `Entry` instead of `EntryPath`).
- Fixes #111 
Fixed #
- Tests
- Haddock
=> [#111] Correct endpoints results in Web API

lib/CLI/Parser.hs, lib/CLI/Types.hs, lib/Coffer/Path.hs, tests/golden/common/common.bats
We had a lot of repeating code in `FromHttpApiData` instances with `CLI.Parse`.
That was fixed.
Basically a lot of low parsing logic moved from `CLI.Parse` to `CLI.Types` and `Coffer.Path`.
It was necessary to avoid cyclic dependencies.
- Resolves #89 
- Tests
- Haddock
=> [#89] Reuse existing megaparsec parsers

Makefile, README.md, scripts/run-bats-tests.sh
There are a few issues with the makefile:
* The `test-all` and `all` targets do the same thing as `test` and `coffer`, so they're redundant
* The `test` target does not include golden tests
* The `test` target calls the doctests executable with `--color`, but doctests does not recognize this option.
This PR:
* removes those redundant targets
* fixes `make test` so that it runs all test suites
* does not call doctest with `--color`
* adds makefile targets for each individual test suite
* updates the readme to reflect these changes
Fixed #120
- Tests
- Haddock
=> [#120] Fix makefile

lib/Web/API.hs, lib/Web/Server.hs
Problem:
We no longer need `QualifiedPath` in `Web API`
Solution:
Removing `QualifiedPath` from `Web API` endpoints
`Web.Server` now makes every `QualifiedPath` without `BackendName`
Fixed #113 
- Tests
- Haddock
=> [#113] Drop support for qualified paths in Web API

coffer.cabal, lib/Coffer/Path.hs, lib/Entry.hs, tests/golden/common/common.bats, tests/server-integration/Common/Common.hs, tests/server-integration/Tag/TagTest.hs, tests/server-integration/Utils.hs
`FieldName`, `EntryTag`, `PathSegment` used unsafe(default text) constructors
for `FromJSON`, `FromJSONKey`  and `FromHttpApiData`
Write new safe instances that use smart `newFieldName` constructor. 
Cover new functionality with bad-case tests
Also corrected previous Error msg.
Fixed #118 
- Tests
- Haddock
=> [#118] Fix unsafe Json http api data instances

README.md, coffer.cabal, lib/Web/Main.hs, package.yaml, tests/server-integration/Common/BootServer.hs, tests/server-integration/Main.hs
Motivation:
Server port wasn't configurable. 
We want to be able specify it via `cmd line option` or `environment variable`
Solution:
Implement configuration by `cmd option`(stronger) & `env variable` for port
- in `lib`:
- added `serverOption`
- added lookup for env var 'COFFER_SERVER_PORT'
- in `tests -> server-integration`
- added cmd option with 8081 port
- added tests for port configuration (tests based on 8079 port)
Fixed #85
- Tests
- Haddock
=> [#85] make the port number configurable

coffer.cabal, lib/Backend.hs, lib/Backend/Commands.hs, lib/Backend/Interpreter.hs, lib/Backend/Vault/Kv.hs, lib/BackendEffect.hs, lib/Backends.hs, lib/CLI/Parser.hs, lib/Coffer/Path.hs, lib/Config.hs, lib/Error.hs, tests/golden/common/common.bats, tests/golden/vault/common.bats, tests/server-integration/Common/Common.hs, tests/server-integration/Vault/Common.hs
We wanted to validate paths not on Path lvl, but on Backend lvl (So each backend validates paths)
- Remove check for allowed symbols
- Added check for not containing '#'
- Added new Effect of `Backend` - `validatePath`
- Added validation for paths in `Backend.Commands`
So it's now cmd responsibility to check if path is valid lies on cmd
- Updated error msg - now they contain info about specific backend
- Added new backend specific tests
Fixed #65
- Tests
- Haddock
=> [#65] Make path's charset rules backend specific

.buildkite/pipeline.yml
Problem: 'nix run' interface has changed with flake addition. However, CI pipeline in this repo still uses the old 'nix run' for which we keep a workaround on our build servers.
Solution: Use 'nix shell' instead.
Fixed #
- Tests
- Haddock
=> [Chore] Don't use old 'nix run' command
